name: Build and Push Docker Images Werf

on:
  pull_request:
    types:
      - closed

jobs:
  trigger-gitlab-review-destroy:
    name: Trigger GitLab Review Stop
    if: startsWith(github.head_ref, 'DEV-')  
    runs-on: ubuntu-latest

    steps:
      - name: Trigger GitLab Pipeline
        run: |
          REPO="${{ vars.GITLAB_REPOSITORY }}"
          PROJECT_ID="${{ secrets.GITLAB_GROUP_ID }}"
          GITLAB_TOKEN="${{ secrets.GITLAB_TRIGGER_TOKEN }}"

          NORMALIZED_GITHUB_BRANCH=$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | cut -c1-63)

          curl --request POST \
            --form token="${GITLAB_TOKEN}" \
            --form ref="DEV-13628-triggered-deploy" \
            --form "variables[NORMALIZED_GITHUB_BRANCH]=${NORMALIZED_GITHUB_BRANCH}" \
            --form "variables[GITHUB_BRANCH]=${{ github.ref_name }}" \
            --form "variables[CI_PIPELINE_SOURCE]=pipeline" \
            --form "variables[CI_ACTION]=destroy" \
            "https://${REPO}/api/v4/projects/${PROJECT_ID}/trigger/pipeline"
