name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - dev
      - DEV-13666-build-images

jobs:
  build-sdk-react:
    name: Build and Push sdk-react
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.monite.com
          username: ${{ vars.GITLAB_BOT_USERNAME }}
          password: ${{ secrets.GITLAB_BOT_ACCESS_TOKEN }}

      - name: Build and Push sdk-react
        run: |
          IMAGE_TAG=sdk-react-${{ github.sha }}
          docker build -t registry.monite.com/monite/frontend/sdkapp:${IMAGE_TAG} -f ./Dockerfile.sdk-react .
          docker push registry.monite.com/monite/frontend/sdkapp:${IMAGE_TAG}

  build-sdk-demo-with-nextjs:
    name: Build and Push sdk-demo-with-nextjs-and-clerk-auth
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.monite.com
          username: ${{ vars.GITLAB_BOT_USERNAME }}
          password: ${{ secrets.GITLAB_BOT_ACCESS_TOKEN }}

      - name: Build and Push sdk-demo-with-nextjs-and-clerk-auth
        run: |
          IMAGE_TAG=sdk-demo-with-nextjs-and-clerk-auth-${{ github.sha }}
          docker build -t registry.monite.com/monite/frontend/sdkapp:${IMAGE_TAG} -f ./Dockerfile.sdk-demo-with-nextjs-and-clerk-auth .
          docker push registry.monite.com/monite/frontend/sdkapp:${IMAGE_TAG}

  build-sdk-demo:
    name: Build and Push sdk-demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.monite.com
          username: ${{ vars.GITLAB_BOT_USERNAME }}
          password: ${{ secrets.GITLAB_BOT_ACCESS_TOKEN }}

      - name: Build and Push sdk-demo
        run: |
          IMAGE_TAG=sdk-demo-${{ github.sha }}
          docker build -t registry.monite.com/monite/frontend/sdkapp:${IMAGE_TAG} -f ./Dockerfile.sdk-demo .
          docker push registry.monite.com/monite/frontend/sdkapp:${IMAGE_TAG}

  build-sdk-drop-in:
    name: Build and Push sdk-drop-in
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.monite.com
          username: ${{ vars.GITLAB_BOT_USERNAME }}
          password: ${{ secrets.GITLAB_BOT_ACCESS_TOKEN }}

      - name: Build and Push sdk-drop-in
        run: |
          IMAGE_TAG=sdk-drop-in-${{ github.sha }}
          docker build -t registry.monite.com/monite/frontend/sdkapp:${IMAGE_TAG} -f ./Dockerfile.sdk-drop-in .
          docker push registry.monite.com/monite/frontend/sdkapp:${IMAGE_TAG}

  build-sdk-demo-nginx:
    name: Build and Push sdk-demo-nginx
    runs-on: ubuntu-latest
    needs: build-sdk-demo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.monite.com
          username: ${{ vars.GITLAB_BOT_USERNAME }}
          password: ${{ secrets.GITLAB_BOT_ACCESS_TOKEN }}

      - name: Build and Push sdk-demo-nginx
        run: |
          BASE_IMAGE_TAG=sdk-demo-${{ github.sha }}
          IMAGE_TAG=sdk-demo-nginx-${{ github.sha }}
          docker pull registry.monite.com/monite/frontend/sdkapp:${BASE_IMAGE_TAG}
          docker build --build-arg BASE_IMAGE=registry.monite.com/monite/frontend/sdkapp:${BASE_IMAGE_TAG} \
                       -t registry.monite.com/monite/frontend/sdkapp:${IMAGE_TAG} -f ./Dockerfile.sdk-demo-nginx .
          docker push registry.monite.com/monite/frontend/sdkapp:${IMAGE_TAG}

  build-sdk-drop-in-nginx:
    name: Build and Push sdk-drop-in-nginx
    runs-on: ubuntu-latest
    needs: build-sdk-drop-in
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.monite.com
          username: ${{ vars.GITLAB_BOT_USERNAME }}
          password: ${{ secrets.GITLAB_BOT_ACCESS_TOKEN }}

      - name: Build and Push sdk-drop-in-nginx
        run: |
          BASE_IMAGE_TAG=sdk-drop-in-${{ github.sha }}
          IMAGE_TAG=sdk-drop-in-nginx-${{ github.sha }}
          docker pull registry.monite.com/monite/frontend/sdkapp:${BASE_IMAGE_TAG}
          docker build --build-arg BASE_IMAGE=registry.monite.com/monite/frontend/sdkapp:${BASE_IMAGE_TAG} \
                       -t registry.monite.com/monite/frontend/sdkapp:${IMAGE_TAG} -f ./Dockerfile.sdk-drop-in-nginx .
          docker push registry.monite.com/monite/frontend/sdkapp:${IMAGE_TAG}
