name: Main Suite

on:
  # Avoid using `pull_request_target`, to prevent insecure actions
  # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main
      - dev
      - v4

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Monorepo
        uses: team-monite/setup-yarn-project-action@c098d54db6f34eb2103eb9cceda484984e8b9bbe

      - name: Build
        run: yarn build

  lint:
    needs: build
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Monorepo
        uses: team-monite/setup-yarn-project-action@c098d54db6f34eb2103eb9cceda484984e8b9bbe

      - name: Lint
        run: yarn lint

  type-checking:
    needs: build
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Monorepo
        uses: team-monite/setup-yarn-project-action@c098d54db6f34eb2103eb9cceda484984e8b9bbe

      - name: Type Check
        run: yarn typecheck

  build-storybook:
    needs: type-checking
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Monorepo
        uses: team-monite/setup-yarn-project-action@c098d54db6f34eb2103eb9cceda484984e8b9bbe

      - name: Build Storybook
        run: yarn storybook:build

  unit-testing:
    needs: build
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Monorepo
        uses: team-monite/setup-yarn-project-action@c098d54db6f34eb2103eb9cceda484984e8b9bbe

      - name: Unit Test
        run: yarn test

  install-playwright-browsers:
    needs: build
    name: Install Playwright Browsers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: 
          - "@monite/sdk-drop-in"
          - "sdk-demo-with-nextjs-and-clerk-auth"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Monorepo
        uses: team-monite/setup-yarn-project-action@c098d54db6f34eb2103eb9cceda484984e8b9bbe

      - name: Install Playwright Browsers
        run: yarn workspace ${{ matrix.workspace }} exec playwright install

      - name: Get Playwright cache directory
        id: playwright-cache
        run: |
          echo "cache-dir=$(yarn workspace ${{ matrix.workspace }} exec playwright --version | head -1 | awk '{print $2}' || echo 'unknown')" >> $GITHUB_OUTPUT
          echo "workspace-safe=$(echo '${{ matrix.workspace }}' | sed 's/@//g' | sed 's/\//-/g')" >> $GITHUB_OUTPUT

      - name: Upload Playwright browsers
        uses: actions/upload-artifact@v4
        with:
          name: playwright-browsers-${{ steps.playwright-cache.outputs.workspace-safe }}
          path: ~/.cache/ms-playwright
          retention-days: 1

  e2e-testing:
    needs: install-playwright-browsers
    name: E2E Playwright Testing
    environment: common
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup Monorepo
        uses: team-monite/setup-yarn-project-action@c098d54db6f34eb2103eb9cceda484984e8b9bbe

      - name: Download all Playwright browsers
        uses: actions/download-artifact@v4
        with:
          pattern: playwright-browsers-*
          path: ~/.cache/ms-playwright
          merge-multiple: true

      - name: E2E Test
        run: yarn e2e
        env:
          MONITE_E2E_APP_ADMIN_CONFIG_JSON: ${{ secrets.MONITE_E2E_APP_ADMIN_CONFIG_JSON }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
          E2E_CLERK_USER_PASSWORD: ${{ secrets.E2E_CLERK_USER_PASSWORD }}
          E2E_CLERK_USER_USERNAME: ${{ secrets.E2E_CLERK_USER_USERNAME }}
          MONITE_PROJECT_CLIENT_ID: ${{ secrets.MONITE_PROJECT_CLIENT_ID }}
          MONITE_PROJECT_CLIENT_SECRET: ${{ secrets.MONITE_PROJECT_CLIENT_SECRET }}
          MONITE_API_URL: ${{ secrets.MONITE_API_URL }}

  translations-validation:
    needs: build
    name: Translations Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Monorepo
        uses: team-monite/setup-yarn-project-action@c098d54db6f34eb2103eb9cceda484984e8b9bbe

      - name: Translations Validator
        run: ./lingui-translations-validator.sh

  files-changed:
    name: Checking modified files
    runs-on: ubuntu-latest
    outputs:
      e2e-npm-tests-dependencies: ${{ steps.changes.outputs.e2e-npm-tests-dependencies }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            e2e-npm-tests-dependencies:
              - 'packages/sdk-react/**'
              - 'packages/rollup-config/**'
              - 'e2e/**'
              - 'package.json'
              - 'yarn.lock'
              - '.changeset/**'
